services:
  - type: static
    name: eventhub-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build --prod
    publishPath: dist/eventhub-frontend
    routes:
      - path: /*
        destination: /index.html
